version: "3.9"
services:
  otterguard_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: otterguard_elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
            - elk
    healthcheck:
      test: curl -XGET 'localhost:9200/_cluster/health?wait_for_status=yellow&timeout=180s&pretty'

  otterguard_kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: otterguard_kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - otterguard_elasticsearch
    networks:
      - elk
    healthcheck:
      test: curl -fs http://localhost:5601/

volumes:
    elasticsearch_data:
        driver: local

networks:
    elk:
        driver: bridge